name: Website Uptime Monitor

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  uptime-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create logs folder
        run: mkdir -p logs

      - name: Monitor websites
        uses: cd-roman/uptime-monitor@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sites: |
            https://gta-6-dun.vercel.app/
          timezone: "Asia/Kolkata"
          timeout: "10"
          success-codes: "200,201,204,301,302"
          max-concurrent: "3"
          create-issue: "true"
# force workflow detection
